name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest  # You can use Amazon Linux 2 if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Change directory to where your Terraform configuration files are
      - name: Terraform Init, Plan, and Apply
        run: |
          cd terraform  # Change directory to where your Terraform files are
          terraform init
          terraform plan
          terraform apply -auto-approve
        if: github.ref == 'refs/heads/main'  # Only apply on main branch

      # Terraform destroy step for pull requests
      - name: Terraform Destroy (optional)
        run: |
          cd terraform  # Change directory to where your Terraform files are
          terraform destroy -auto-approve
        if: github.event_name == 'pull_request'  # Cleanup for PRs
